services:
  - type: static_site
    name: hybrid-value-betting-model
    repo: https://github.com/skizzunni/hybrid-value-betting-model
    branch: main
    buildCommand: "npm install && npm run build"
    publishPath: "dist"
