services:
  - type: web_service
    name: hybrid-value-betting-backend
    repo: https://github.com/skizzunni/hybrid-value-betting-model
    branch: main
    rootDir: server
    buildCommand: "cd server && npm install && npm run build"
    startCommand: "cd server && npm start"
    envVars:
      - key: NODE_ENV
        value: production
